
# src/lang.py - Localization for PV Forecasting Dashboard

TR = {
    'EN': {
        'page_title': "PV Forecasting Pipeline",
        'sidebar_settings': "⚙️ Global Settings",
        'lang_select': "Language / Bahasa",
        'data_insights': "🔎 Data Insights",
        'data_prep': "🛠️ Data Prep & Features",
        'training_center': "🏗️ Training Center",
        'batch_experiments': "🚀 Batch Experiments",
        'optuna_tuning': "🎯 Optuna Tuning",
        'prediction_eval': "📈 Prediction/Eval",
        'leaderboard': "🏆 Leaderboard",
        'target_testing': "🔄 Target Testing",
        'troubleshooting': "🛠️ Troubleshooting",
        'status_ready': "Ready",
        'status_missing': "Missing",
        'status_present': "Present",
        'data_preprocessed': "Data Preprocessed",
        'model_trained': "Model Trained",
        'target_data': "Target Data",
        'active_arch': "Active Architecture",
        'not_ready': "Not Ready",
        'yes': "Yes",
        'no': "No",
        'start_prep': "▶️ Start Preprocessing",
        'start_train': "🚀 Start Model Training",
        'run_eval': "▶️ Run Evaluation",
        'run_batch': "🔥 Run Batch Training Now",
        'add_to_queue': "➕ Add to Queue",
        'current_queue': "📋 Current Queue",
        'hp_config': "Model Architecture & Hyperparameters",
        'batch_manager_title': "🚀 Batch Experiment Manager",
        'batch_info': "Build a training queue for various models and run them all automatically.",
        'add_exp': "Add to Queue",
        'exp_name': "Experiment Name",
        'architecture': "Architecture",
        'config_hp': "Configure Hyperparameters",
        'config_data_feat': "Configure Data & Features",
        'data_version_select': "Preprocessed Data Version",
        'feature_groups_info': "Feature Groups (Only if 'Current (Dynamic)' is selected)",
        'current_dynamic': "Current (Dynamic)",
        'run_batch_btn': "🔥 Run Batch Now",
        'add_to_queue_success': "✅ Added to queue!",
        'current_queue': "📋 Current Queue",
    },
    'ID': {
        'page_title': "Pipeline Prediksi PV",
        'sidebar_settings': "⚙️ Pengaturan Global",
        'lang_select': "Bahasa / Language",
        'data_insights': "🔎 Analisis Data",
        'data_prep': "🛠️ Persiapan Data & Fitur",
        'training_center': "🏗️ Pusat Training",
        'batch_experiments': "🚀 Eksperimen Batch",
        'optuna_tuning': "🎯 Optimasi Optuna",
        'prediction_eval': "📈 Prediksi/Evaluasi",
        'leaderboard': "🏆 Papan Skor",
        'target_testing': "🔄 Uji Target",
        'troubleshooting': "🛠️ Troubleshooting",
        'status_ready': "Siap",
        'status_missing': "Belum Ada",
        'status_present': "Ada",
        'data_preprocessed': "Data Terproses",
        'model_trained': "Model Terlatih",
        'target_data': "Data Target",
        'active_arch': "Arsitektur Aktif",
        'not_ready': "Belum Siap",
        'yes': "Ya",
        'no': "Tidak",
        'start_prep': "▶️ Mulai Preprocessing",
        'start_train': "🚀 Mulai Pelatihan Model",
        'run_eval': "▶️ Jalankan Evaluasi",
        'run_batch': "🔥 Jalankan Batch Sekarang",
        'add_to_queue': "➕ Tambahkan ke Antrean",
        'current_queue': "📋 Antrean Saat Ini",
        'hp_config': "Arsitektur Model & Hyperparameter",
        'batch_manager_title': "🚀 Manajer Eksperimen Batch",
        'batch_info': "Bangun antrean training untuk berbagai model dan jalankan semuanya secara otomatis.",
        'add_exp': "Tambah ke Antrean",
        'exp_name': "Nama Eksperimen",
        'architecture': "Arsitektur",
        'config_hp': "Konfigurasi Hyperparameter",
        'config_data_feat': "Konfigurasi Data & Fitur",
        'data_version_select': "Versi Data Preprocessed",
        'feature_groups_info': "Grup Fitur (Hanya jika 'Current (Dynamic)' dipilih)",
        'current_dynamic': "Aktif (Dinamis)",
        'run_batch_btn': "🔥 Jalankan Batch Sekarang",
        'add_to_queue_success': "✅ Berhasil ditambah ke antrean!",
        'current_queue': "📋 Antrean Saat Ini",
    }
}

def gt(key, lang='ID'):
    """Get translation for a key."""
    return TR.get(lang, TR['ID']).get(key, key)
